apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-green
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    version: green
    app: webapp
  template:
    metadata:
      labels:
        version: green
        app: webapp
    spec:
      containers:
      - name: webapp
        imagePullPolicy: Always
        image: 703587889398.dkr.ecr.us-east-1.amazonaws.com/hello-world:green
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
