apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-v1
  labels:
    tier: frontend
    heritage: helm
    template: webapp
spec:
  replicas: 2
  selector:
    tier: frontend
    version: v1
  template:
    metadata:
      labels:
        tier: frontend
        heritage: helm 
        version: v1
    spec:
      containers:
      - name: webapp-v1
        imagePullPolicy: Always
        image: 703587889398.dkr.ecr.us-east-1.amazonaws.com/hello-world:latest
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
